services:
  wordpress:
    image: wordpress:latest
    container_name: itlab_wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: wp-database # same as the service name of the database
      WORDPRESS_DB_USER: "user"
      WORDPRESS_DB_PASSWORD: "password"
      WORDPRESS_DB_NAME: "wordpress"
    # volumes:
    #   - wp_data:/var/www/html
    depends_on: # Ensure database starts before wordpress
      - wp-database

  wp-database:
    image: mysql:5.7
    # image: mysql:8.0
    container_name: itlab_wordpress_db
    restart: always
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "rootpassword"
    # volumes:
    #   - db_data:/var/lib/mysql

# Presist data volumes
# volumes:
#   wp_data:
#   db_data:
