services:
  wordpress:
    image: wordpress:6-fpm-alpine
    container_name: itlab_wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: wp-database # same as the service name of the database
      WORDPRESS_DB_USER: "{{ db_user }}"
      WORDPRESS_DB_PASSWORD: "{{ db_password }}"
      WORDPRESS_DB_NAME: "{{ db_name }}"
    volumes:
      - wp_data:/var/www/html # volumen_name:/path/in/container
    depends_on:
      - wp-database

  wp-database:
    # image: mysql:5.7
    image: mysql:8.0
    container_name: itlab_wordpress_db
    restart: always
    environment:
      MYSQL_DATABASE: "{{ db_name }}"
      MYSQL_USER: "{{ db_user }}"
      MYSQL_PASSWORD: "{{ db_password }}"
      MYSQL_ROOT_PASSWORD: "{{ db_root_password }}"
    volumes:
      - db_data:/var/lib/mysql # volumen_name:/path/in/container

# Data volumes definitions
volumes:
  wp_data:
  db_data:
